name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,30 4-22 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Timezone
        run: sudo timedatectl set-timezone Europe/Berlin
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go version
      - run: go test -v ./...
      - name: run
        run: |
          mkdir public
          go run . > public/index.html
          mv news-archive.json public/
          cp manifest.json public/
          cp -r images public/
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
